services:
  postgres:
    image: postgres:latest
    container_name: barbershop
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

volumes:
  .postgres-data:
