import type { Metadata } from "next"
import { Nunito_Sans as FontSans } from "next/font/google"
import "./globals.css"

const fontSans = FontSans({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body className={fontSans.className}>{children}</body>
    </html>
  )
}
